ALTER TABLE nodes ADD COLUMN sort_order INTEGER NOT NULL DEFAULT 0 CHECK (sort_order BETWEEN 0 AND 999999);
ALTER TABLE inbounds ADD COLUMN sort_order INTEGER NOT NULL DEFAULT 0 CHECK (sort_order BETWEEN 0 AND 999999);
